# Generated by Django 4.2.8 on 2024-12-09 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(choices=[('civil_servant', 'Civil Servant'), ('repayment', 'Repayment'), ('loan_details', 'Loan Details')], max_length=50)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                # ('created_by', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_import_status_67db40_idx'), models.Index(fields=['table_name', 'created_at'], name='core_import_table_n_1ac182_idx')],
            },
        ),
    ]
