# Generated by Django 4.2.8 on 2024-12-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importlog',
            name='created_by',
        ),
    ]
